"""
Git Hooks 管理器
实现 Git hooks 的安装、卸载和触发机制
"""

import platform
import stat
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Optional

from git import Repo


class HookType(str, Enum):
    POST_COMMIT = "post-commit"
    POST_MERGE = "post-merge"
    POST_CHECKOUT = "post-checkout"
    PRE_PUSH = "pre-push"


@dataclass
class HookConfig:
    hook_type: HookType
    enabled: bool = True
    command: Optional[str] = None
    async_execution: bool = True


@dataclass
class HookResult:
    success: bool
    hook_type: HookType
    output: str = ""
    error: str = ""
    duration_ms: float = 0.0


POST_COMMIT_HOOK_TEMPLATE = '''#!/bin/sh
# Auto-generated by Python Wiki
# Triggers incremental wiki update after commit

pywiki hook-trigger post-commit "$GIT_COMMIT" 2>/dev/null &
'''

POST_MERGE_HOOK_TEMPLATE = '''#!/bin/sh
# Auto-generated by Python Wiki
# Triggers wiki update after merge

pywiki hook-trigger post-merge 2>/dev/null &
'''

POST_CHECKOUT_HOOK_TEMPLATE = '''#!/bin/sh
# Auto-generated by Python Wiki
# Triggers wiki check after branch checkout

pywiki hook-trigger post-checkout "$1" "$2" 2>/dev/null &
'''

WINDOWS_HOOK_TEMPLATE = '''@echo off
REM Auto-generated by Python Wiki
REM Triggers incremental wiki update after commit

start /B pywiki hook-trigger post-commit %GIT_COMMIT%
'''

HOOK_TEMPLATES = {
    HookType.POST_COMMIT: POST_COMMIT_HOOK_TEMPLATE,
    HookType.POST_MERGE: POST_MERGE_HOOK_TEMPLATE,
    HookType.POST_CHECKOUT: POST_CHECKOUT_HOOK_TEMPLATE,
}


class GitHooksManager:
    """
    Git Hooks 管理器
    管理 Wiki 自动更新相关的 Git hooks
    """

    def __init__(
        self,
        repo_path: Path,
        on_trigger: Optional[Callable[[HookType, dict[str, Any]], None]] = None,
    ):
        self.repo_path = Path(repo_path)
        self.on_trigger = on_trigger
        self._repo: Optional[Repo] = None
        self._hooks_dir: Optional[Path] = None

    @property
    def repo(self) -> Repo:
        if self._repo is None:
            self._repo = Repo(self.repo_path)
        return self._repo

    @property
    def hooks_dir(self) -> Path:
        if self._hooks_dir is None:
            self._hooks_dir = self.repo_path / ".git" / "hooks"
        return self._hooks_dir

    def is_git_repo(self) -> bool:
        try:
            _ = self.repo
            return True
        except Exception:
            return False

    def install_hooks(
        self,
        hook_types: Optional[list[HookType]] = None,
        force: bool = False,
    ) -> dict[HookType, bool]:
        """
        安装 Git hooks

        Args:
            hook_types: 要安装的 hook 类型，None 表示安装全部
            force: 是否覆盖已存在的 hooks

        Returns:
            安装结果字典
        """
        if not self.is_git_repo():
            return {}

        if hook_types is None:
            hook_types = [HookType.POST_COMMIT, HookType.POST_MERGE]

        results: dict[HookType, bool] = {}

        self.hooks_dir.mkdir(parents=True, exist_ok=True)

        for hook_type in hook_types:
            success = self._install_single_hook(hook_type, force)
            results[hook_type] = success

        return results

    def _install_single_hook(self, hook_type: HookType, force: bool) -> bool:
        try:
            hook_path = self.hooks_dir / hook_type.value

            if hook_path.exists() and not force:
                existing_content = hook_path.read_text(encoding="utf-8")
                if "pywiki hook-trigger" in existing_content:
                    return True
                return False

            if platform.system() == "Windows":
                content = WINDOWS_HOOK_TEMPLATE
                hook_path = self.hooks_dir / f"{hook_type.value}.bat"
            else:
                content = HOOK_TEMPLATES.get(hook_type, POST_COMMIT_HOOK_TEMPLATE)

            hook_path.write_text(content, encoding="utf-8")

            if platform.system() != "Windows":
                hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

            return True

        except Exception:
            return False

    def uninstall_hooks(self, hook_types: Optional[list[HookType]] = None) -> dict[HookType, bool]:
        """
        卸载 Git hooks

        Args:
            hook_types: 要卸载的 hook 类型，None 表示卸载全部

        Returns:
            卸载结果字典
        """
        if not self.is_git_repo():
            return {}

        if hook_types is None:
            hook_types = list(HookType)

        results: dict[HookType, bool] = {}

        for hook_type in hook_types:
            success = self._uninstall_single_hook(hook_type)
            results[hook_type] = success

        return results

    def _uninstall_single_hook(self, hook_type: HookType) -> bool:
        try:
            hook_path = self.hooks_dir / hook_type.value
            win_hook_path = self.hooks_dir / f"{hook_type.value}.bat"

            removed = False

            for path in [hook_path, win_hook_path]:
                if path.exists():
                    content = path.read_text(encoding="utf-8")
                    if "pywiki hook-trigger" in content:
                        path.unlink()
                        removed = True

            return removed

        except Exception:
            return False

    def get_installed_hooks(self) -> list[HookType]:
        """
        获取已安装的 hooks 列表

        Returns:
            已安装的 hook 类型列表
        """
        installed: list[HookType] = []

        if not self.is_git_repo():
            return installed

        for hook_type in HookType:
            hook_path = self.hooks_dir / hook_type.value
            win_hook_path = self.hooks_dir / f"{hook_type.value}.bat"

            for path in [hook_path, win_hook_path]:
                if path.exists():
                    try:
                        content = path.read_text(encoding="utf-8")
                        if "pywiki hook-trigger" in content:
                            installed.append(hook_type)
                            break
                    except Exception:
                        pass

        return installed

    def trigger_hook(
        self,
        hook_type: HookType,
        context: Optional[dict[str, Any]] = None,
    ) -> HookResult:
        """
        触发 hook 执行

        Args:
            hook_type: Hook 类型
            context: 执行上下文

        Returns:
            执行结果
        """
        import time

        start_time = time.time()
        context = context or {}

        try:
            if hook_type == HookType.POST_COMMIT:
                result = self._handle_post_commit(context)
            elif hook_type == HookType.POST_MERGE:
                result = self._handle_post_merge(context)
            elif hook_type == HookType.POST_CHECKOUT:
                result = self._handle_post_checkout(context)
            else:
                result = HookResult(
                    success=False,
                    hook_type=hook_type,
                    error=f"Unknown hook type: {hook_type}",
                )

        except Exception as e:
            result = HookResult(
                success=False,
                hook_type=hook_type,
                error=str(e),
            )

        result.duration_ms = (time.time() - start_time) * 1000

        if self.on_trigger:
            try:
                self.on_trigger(hook_type, context)
            except Exception:
                pass

        return result

    def _handle_post_commit(self, context: dict[str, Any]) -> HookResult:
        commit_hash = context.get("commit_hash")
        if not commit_hash:
            try:
                commit_hash = self.repo.head.commit.hexsha
            except Exception:
                pass

        return HookResult(
            success=True,
            hook_type=HookType.POST_COMMIT,
            output=f"Post-commit triggered for {commit_hash}",
        )

    def _handle_post_merge(self, context: dict[str, Any]) -> HookResult:
        return HookResult(
            success=True,
            hook_type=HookType.POST_MERGE,
            output="Post-merge triggered",
        )

    def _handle_post_checkout(self, context: dict[str, Any]) -> HookResult:
        from_branch = context.get("from_branch", "unknown")
        to_branch = context.get("to_branch", "unknown")

        try:
            to_branch = self.repo.active_branch.name
        except Exception:
            pass

        return HookResult(
            success=True,
            hook_type=HookType.POST_CHECKOUT,
            output=f"Post-checkout triggered: {from_branch} -> {to_branch}",
        )

    def get_hooks_status(self) -> dict[str, Any]:
        """
        获取 hooks 状态

        Returns:
            状态信息字典
        """
        installed = self.get_installed_hooks()

        return {
            "is_git_repo": self.is_git_repo(),
            "hooks_dir": str(self.hooks_dir),
            "installed_hooks": [h.value for h in installed],
            "platform": platform.system(),
        }
